---
title: "Past Experiences"
output: html_document
---

<br> 

***

## Teaching and research experience

<br>

- **Oct. 2020 - Sep. 2022 -- Teaching Assistant** \
Economics Department, Université Paris 8   

- **Sep. 2019 - May. 2020 -- Young Research Fellow** \
[**Center of History of Political Economy (CHOPE)**](https://hope.econ.duke.edu/node/1753), Duke University  
 
- **Aug. 2019 -- Research Assistant** \
Institut National d'Etudes Démographiques (INED)\
[**Project TOFLIT 18**](https://toflit18.hypotheses.org/603) « Transformations of the French Economy through the Lens of International Trade, 1716-1821 »

- **Jan.2019 - Jul. 2019 -- Young Invited Researcher** \
[**Centre Interdisciplinaire de Recherche sur la Science et la Technologie (CIRST)**](https://cirst2.openum.ca/publications/notes-de-recherche/?person=6164)\
Université du Québec A Montréal (UQAM)\
Local supervisor: [**Yves Gingras**](https://cirst.uqam.ca/chercheurs-chercheuses/gingras-yves/)

- **Sep. 2018 - Dec. 2018 -- Teaching Assistant** \
Economics Department, Université Paris 8

- **Feb. 2018 -- Research Assistant** \
Institut National d'Etudes Démographiques (INED)\
[**Project TOFLIT 18**](https://toflit18.hypotheses.org/603) « Transformations of the French Economy through the Lens of International Trade, 1716-1821 »
    
- **Oct. 2017 - Jan. 2018 -- Young Invited Researcher** \
[**Centre Interdisciplinaire de Recherche sur la Science et la Technologie (CIRST)**](https://cirst2.openum.ca/publications/notes-de-recherche/?person=6164)\
Université du Québec A Montréal (UQAM)\
Local supervisor: [**Yves Gingras**](https://cirst.uqam.ca/chercheurs-chercheuses/gingras-yves/)

- **Jul. 2017 - Aug. 2017 -- Research Assistant** \
Université Paris Dauphine\
[**Project TOFLIT 18**](https://toflit18.hypotheses.org/603) « Transformations of the French Economy through the Lens of International Trade, 1716-1821 »

- **Jan. 2017 - Jun. 2017 -- Lecturer in History of Economic Thought** \
Economics Department, Université de Tours François Rabelais

- **Jul. 2016 -- Research Assistant** \
Institut National d’Etudes Démographiques (INED) \
[**Project TOFLIT 18**](https://toflit18.hypotheses.org/603) « Transformations of the French Economy through the Lens of International Trade, 1716-1821 »

- **Jul. 2015 -- Research Assistant** \
Institut National d’Etudes Démographiques (INED) \
[**Project TOFLIT 18**](https://toflit18.hypotheses.org/603) « Transformations of the French Economy through the Lens of International Trade, 1716-1821 »

***

## Grants 

<br>

- 2019-2020 -- Final Year Fellowship from the Center for the History of Political Economy (CHOPE) at Duke University

- 2017 -- Grant from the Chancellerie des universités de Paris

- 2017 -- Grant for international mobility of Phd students (AMI Doctorants) from the Région Île-de-France

- 2017 -- Grant for international mobility from the Office Franco-Québecois pour la Jeunesse (OFQJ)

<br><br>