---
title: "Publications"
---

<br>

<div class="mycontent">

## Research Articles

<hr style="height: 1px;background-color: #2c3e50">

- 2026 -- "Land, Space or Cities: A History of 'Urban Economics' as a Field" (with [Beatrice Cherrier](https://beatricecherrier.wordpress.com/about/)), *Journal of the History of Economic Thought* \
<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4450141" class="btn btn-primary btn-sm"> 
**SSRN**
</a>
<a href="https://github.com/anthonyrebours/history_urban_economics" class="btn btn-primary btn-sm">
**CODE**
</a>
<a href="online_appendix_urban.html" class="btn btn-primary btn-sm"> 
**ONLINE APPENDIX** 
</a>

- *In revision* -- "History of IAFFE Presidents’ Trajectories and Cognitive Interactions" (with [Rebeca Gomez Betancourt](https://triangle.ens-lyon.fr/spip.php?article1356) and [Camila Orozco Espinel](https://univ-reims.academia.edu/CamilaOrozcoEspinel))\
<a class="btn btn-primary disabled btn-sm"> 
**SSRN** 
</a> 
<a href="Online_Appendix_FE.html" class="btn btn-primary btn-sm"> 
**ONLINE APPENDIX**
</a>

<br>

## Working Articles

<hr style="height: 1px;background-color: #2c3e50">

- 2024 -- "The Reception of Dixit-Stiglitz Monopolistic Competition Model"\
<a class="btn btn-primary disabled btn-sm">
**DRAFT** 
</a> 
<a class="btn btn-primary disabled btn-sm">
**ONLINE APPENDIX**
</a>

- 2023 -- "The Diffusion of Monocentric City Models of Land Use: How AMM Became Mainstream"\
<a class="btn btn-primary disabled btn-sm">
**DRAFT** 
</a>

- 2022 -- "In Research of a Disciplinary Identity: The Institutionalization of Regional Science"\
<a class="btn btn-primary disabled btn-sm"> 
**DRAFT**
</a>
<a class="btn btn-primary disabled btn-sm">
**ONLINE APPENDIX**
</a>

- 2020 -- "‘New Economic Geography’ and The Evolution of the Relationships Between Economics and Geography (1980-2015)"\
<a class="btn btn-primary disabled btn-sm"> 
**SSRN** 
</a>

<br>

## Blog Posts

<hr style="height: 1px;background-color: #2c3e50">

- 2020 -- “Cities, Land and Space: A History of ‘Urban Economics’ As a Field” (with [Beatrice
Cherrier](https://beatricecherrier.wordpress.com/about/))\
<a href="https://hscif.org/economists-in-the-city-cherrierrebours/" class="btn btn-primary btn-sm"> 
**POST**
</a>


- 2020 -- "The institutionalization of Regional Science in the Shadow of Economics”\
<a href="https://hscif.org/economists-in-the-city-rebours/" class="btn btn-primary btn-sm"> **POST**
</a>

<br>

## Presentations

<hr style="height: 1px;background-color: #2c3e50">

- **June 2023 -- "Do Feminists Economists Form a Community of Scholars?" (with Rebeca Gomez Betancourt and Camila Orozco Espinel)**\
Presented in distance [26th Annual Conference of the European Society for the History of Economic Thought (ESHET)](https://www.eshet-conference.net/liege/ed2023/program/)


- **December 2022 -- "The Diffusion of the Monocentric City Model"**\
Workshop of the [Society for the History of Recent Social Science (HISRESS)](https://hisress.org/)  “Transforming Homo Economicus”\
Institution National d'Etudes Démographique (INED)


- **June 2022 -- "Do Feminists economists form a communityof scholars?" (with Rebeca Gomez Betancourt and Camila Orozco Espinel)**\
[Annual Conference of International Association For Feminist Economics (IAFFE)](https://www.iaffe.org/2022-annual-conference)\
Graduate Institute of International and Development Studies (Genève)


- **June 2022 -- "In Research of a Disciplinary Identity: The Institutionalization of Regional Science"**\
Presentation at conference of the [Réseau en Epistémologie et en Histoire de la Pensée Economique Récente (Rehpere)](https://rehpere.org/) “Recent Shifts in the Boundaries Of Economics: Philosophy and History”\
Maison des sciences économiques de la Sorbonne (Université Paris 1)


- **December 2021 -- "In Research of a Disciplinary Identity: The Institutionalization of Regional Science"**\
Workshop of the [Society for the History of Recent Social Science (HISRESS)](https://hisress.org/) “Economics and Other Social Sciences”\
Institution National d'Etudes Démographique (INED)


- **May 2021 -- "Cities, Land and Space: A history of ‘Urban Economics’ as a field" (with [with Beatrice Cherrier](https://beatricecherrier.wordpress.com/about/))**\
Zoom Seminar of Max Planck Science Po Center (MaxPo)


- **March 2021 -- "Cities, Land and Space: A history of ‘Urban Economics’ as a field" (with Beatrice Cherrier)**\
Zoom Seminar of economics department of New York University (NYU) at Abu Dhabi


- **January 2020 -- "City and Space: The History of Urban Economics"**\ 
Presentation at the workshop of the [Center for the History of Political Economy (CHOPE)](https://hope.econ.duke.edu/)\
Duke University


- **June 2019 -- "Les interactions entre la géographie et l’économie (1980-2015) : une histoire bibliométrique"**\
Presentation at Journées d’études of the Charles Gides Association "Les Evolutions des frontières disciplinaires de l’économie avec les autres sciences"\
Université TELUQ (Montréal)


- **June 2019 -- "Les interactions entre la géographie et l’économie (1980-2015) : une histoire bibliométrique"**\
Presentation at the [Centre Interuniversitaire de Recherche sur la Science et la Technologie (CIRST)](https://cirst.uqam.ca/)\
Université du Québec A Montréal (UQAM)


- **May 2019 -- "The Evolution of the Relationships Between Economy and Geography (1980-2015):
A Bibliometric Study"**\
Young Scholar presentation for the [23rd Annual Conference of European Society for the History of Economic Thought (ESHET)](https://www.eshet.net/list-of-past-conferences/)\
Science Po Lille


- **May 2019 -- "The Evolution of the Relationships Between Economy and Geography (1980-2015):
A Bibliometric Study"**\
Workshop for Young Scholars "The Uses of Scientometrics for the History of Social Sciences" (co-organised with [Alexandre Truc](https://sites.google.com/view/alexandre-truc/home-and-contact) and [Loïc Charles](https://www.ined.fr/fr/recherche/chercheurs/Charles+Lo%C3%AFc))\
Université Paris 8

- **December 2018 -- "The Evolution of the Relationships Between Economy and Geography (1980-2015):
A Bibliometric Study"**\
[Séminaire du LED](https://sites.google.com/site/up8led/activities/seminars/archives)\
Université Paris 8

- **June 2018 -- "The Evolution of the Relationships Between Economy and Geography (1980-2015):
A Bibliometric Study"**\
Young Scholar presentation for the [45th Annual Conference of History of Economic Society (HES)](https://historyofeconomics.org/wp-content/uploads/2018/06/2018-Conference-Program-finalBW.pdf)\
Loyola University Chicago

<br>

</div>

